### ISSUE TITLE
URL coordinate parameters rotate map to bounds

### ISSUE THREAD

**Issue by bwellington** [axismaps/pilotplan#25]
The `fitbounds()` method automatically resets the map to a bearing of 0, and there doesn't appear to be a way to set an initial map extent. I think we'll need to use the `jumpTo()` method for setting initial bounds. To do this, I'll need to calculate the map's center, zoom level, bearing, and pitch. I know how to get center, and bearing and pitch won't change, but I do not know how to calculate zoom level for given coordinate bounds, screen size, and non-zero bearing.

Another strategy would be to convert the map's bounds, which are calculated based on a bearing of 0, to a new bounding box based on a non-zero bearing, kind of like drawing a rectangle around a rotated rectangle. 

Anyone have any experience with something like this?

**Comment by bwellington** [comment]
I have an idea--take the coordinates of each corner of the screen, generate a bounding box for these four sets of coordinates, then zoom to that bounding box. Although I suppose `fitBounds()` could potentially rotate the screen to be upside down. I'll test and see what happens

**Comment by davidheyman** [comment]
Instead of a bounding box, can we just store the zoom, the center coordinate from getCenter(), and the rotation (which will either be 0 or -72)? This is how the initial coordinates for the map are stored. We don’t need to worry about the extents being 100% precise between devices.
