### ISSUE TITLE
Allow horizontal scrolling of thumbnails in the historical overlays filmstrip

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/pilotplan#28]

**Comment by bwellington** [comment]
Updated. Do we need to increase the size of the footer so the scrollbar doesn't cause the filmstrip items to shift in position? When they shift, they slightly misalign with the "show all" button. I'm not sure if this matters.

**Comment by bcsheesley** [comment]
@bwellington In what browser are you seeing the shifting? I don't see it (or am not noticing it) in FF, Safari, or Chrome.

**Comment by bwellington** [comment]
I just mean the images become slightly out of alignment with the "show all" button. I'm probably being neurotic here:
![alignment](https://user-images.githubusercontent.com/11998214/46104571-aeb82800-c1a1-11e8-85d8-bb8e7d37113a.jpg)

**Comment by bcsheesley** [comment]
Okay. Maybe it's a Mac versus PC thing. I don't have this issue. I'd be okay ignoring it since it's probably only a case for some users some of the time, but I do share your neurosis to some degree!
