### ISSUE TITLE
Add zoom controls (with rotation / pitch) and a reset button to return to initial extent (and rotation)

### ISSUE THREAD

**Issue by davidheyman** [axismaps/pilotplan#3]

**Comment by davidheyman** [comment]
The only reset button we need is just one to reset the rotation back to -72°. No need for a zoom to full extent button. It should only appear when the rotation changes.

@bcsheesley Can you design an icon for the rotation reset button? Perhaps just the airplane design of the city oriented north / south along the axis?

**Comment by bcsheesley** [comment]
Here's two options for this icon. One is the airplane and the other is a smaller airplane with a rotate arrow around it.

https://www.dropbox.com/sh/ynwe7irzve9yzhz/AAArcw5zK1n_0ftduMfCZ4xta?dl=0

**Comment by davidheyman** [comment]
I think the rotate arrow removes all doubt. Thanks!

**Comment by bwellington** [comment]
Updated

**Comment by bcsheesley** [comment]
Looks good to me. My only question is whether the reset button should only appear when needed (instead of all the time).

**Comment by davidheyman** [comment]
Yes please. The button should only appear when pressing it would actually do something.

The alternative to this would be toggling between -72° and 0° rotation on button press, but I think that might be tricky to convey with an icon.
