### ISSUE TITLE
Click search pulse

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/pilotplan#36]
Unlike Rio, the pulse does not always loop the same number of times or animate at the same pace. Could it be something weird with the new gif I uploaded?

**Comment by davidheyman** [comment]
Since the results appear almost instantaneously, I’d be happy if this animation was very short. We just need something that says 'your click was registered' right?

**Comment by bcsheesley** [comment]
Yeah. Looping through once is fine by me, to keep it quick. I'd just prefer that whatever animation plays, it be consistent.

I think the pulse mostly says "your click was registered" but also a little bit of "your click includes things within a certain radius".

**Comment by bwellington** [comment]
I forgot that I'd had to do some stuff for Rio to make it animate consistently. Updated--let me know if this fixes it. It should be animating through once (pulse is 900ms, right?)
