### ISSUE TITLE
Close footer and add message when jumping to years without image content

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/pilotplan#37]
![screen shot 2018-09-24 at 2 41 05 pm](https://user-images.githubusercontent.com/4501388/45974786-0de23500-c008-11e8-8779-f0a510666c6f.png)

**Comment by bwellington** [comment]
How's this work?

**Comment by bcsheesley** [comment]
That works for me. Just need to hide the message when the footer is collapsed.

![screen shot 2018-09-26 at 1 51 51 pm](https://user-images.githubusercontent.com/4501388/46102198-5ed26480-c193-11e8-8c5e-317023d6594d.png)
