### ISSUE TITLE
Map sometimes can't get search feature geojson after panning/zooming

### ISSUE THREAD

**Issue by bwellington** [axismaps/pilotplan#44]

**Comment by bwellington** [comment]
I've started implementing this (doesn't always work yet because I need to wait for the tiles to completely load before querying), but it seems really jarring to me. Should I continue with this strategy? One other thought is re-running the search at the end of zooming to a feature, so only available features will show up in the sidebar.

**Comment by bwellington** [comment]
This is updated. I current have it set to animate to the original search location, which I think is less jarring. But I can easily change the animation speed or turn off the animation.

**Comment by davidheyman** [comment]
@bcsheesley I'd like to get your take on an alternative solution for this. I understand why it is necessary, but things like this should be avoided.

![2018-10-11_11-33-29](https://user-images.githubusercontent.com/791434/46799366-8fe29580-cd4c-11e8-97e1-1b8f5086d9f4.gif)

**Comment by bwellington** [comment]
Yeah, it's not great. We could try re-running the search after moving/zooming, gray out features that become unavailable (and maybe not display any new features that become available). Or just update the sidebar with new search results on every zoom (which would be a lot easier). If we do something like this, is there a way to indicate in the sidebar that search results are dependent on zoom level? Another thought: we keep things as they are, but only return to original zoom if a feature comes back as unavailable. So we won't have a situation where the map zooms way out then zooms right back in to the same area. We'd only return to the original zoom level if we actually have to.

**Comment by bwellington** [comment]
Updated. Now the map only returns to the original search position if a feature is unavailable. I think this mostly solves the issue, or at least improves things, but it still isn't perfect.

**Comment by davidheyman** [comment]
This is great. Good call with checking before adjusting position.
