### ISSUE TITLE
Add title and year to exported maps

### ISSUE THREAD

**Issue by davidheyman** [axismaps/pilotplan#46]
Here's how they look in imagineRio

![rio-1921](https://user-images.githubusercontent.com/791434/46811840-71d85d80-cd6b-11e8-8b03-14abe794712d.png)

Here's the Canvas code if you need a starting point:

```js
context.fillStyle = 'rgba( 230, 230, 230, 0.8 )';
    context.fillRect( 0, 0, dimensions.x, titleHeight );
    context.fillStyle = '#666';
    context.fillRect( 0, titleHeight - 1, dimensions.x, 1 );
    context.font = '100 30px Raleway';
    context.fillText( req.params.lang == 'en' ? 'imagineRio' : 'imagináRio', 20, 35 );
  
    context.font = 'bold 20px Raleway';
    context.fillText( req.params.year, dimensions.x - 100, 35 );
```

**Comment by bwellington** [comment]
In this case the canvas context is webgl, so the API is totally different. I'll need to dig into this a bit, unless you have an examples of drawing rectangles + text with webgl.

**Comment by bwellington** [comment]
Updated. Let me know how this should be styled.
