### ISSUE TITLE
Legend isn't entirely representative of actual map symbology

### ISSUE THREAD

**Issue by davidheyman** [axismaps/pilotplan#47]

**Comment by davidheyman** [comment]
@bcsheesley Can you put together a CSV spreadsheet we can use for the legend? I think we can get away with column names of:

feature_name | svg | color

But let me know if it has to be more complex than this.

**Comment by bcsheesley** [comment]
Here's a link to the spreadsheet. I'll stick any new SVGs we need here as well.

https://www.dropbox.com/s/pptkcea5n255uzj/legend.csv?dl=0

**Comment by bcsheesley** [comment]
This looks great!
