### ISSUE TITLE
Layer highlighting should respect minimum zoom for each layer

### ISSUE THREAD

**Issue by davidheyman** [axismaps/pilotplan#48]
Clicking on "Live" in the legend will zoom the map out beyond where the buildings layer is visible. We need to prevent the map from zooming out that far, even if it means not every feature can be drawn.

**Comment by bwellington** [comment]
Frustrating enough, with the mapbox-gl `fitBounds` method you can specify a maximum zoom level but not a minimum zoom level. If I do something like interrupt the zoom animation at a certain zoom threshold (I'm guessing this is possible) the zoom animation would come to an abrupt stop. How difficult would it be to just revise `extents.json`? Alternatively, do you know of a way to calculate what a zoom level will be given coordinate boundaries and screen dimensions? This would allow me to dynamically modify the bounding box before zooming.

**Comment by davidheyman** [comment]
What if you created a new map instance that wasn’t attached to the DOM? Then you could use that to zoom to the actual bounds then adjust the zoom and take the new bounds.

**Comment by bwellington** [comment]
Updated, but still doesn't work so well. One issue is the minzoom levels don't seem to be working correctly--the "live" layer vanishes at a greater zoom level than its minimum of 11. I think there may be other tile/data issues going on here that I need to investigate.

**Comment by bcsheesley** [comment]
I don't think I understand all the issues here, but I can attest to the role of minzoom levels. I adjusted the zoom extent on some layers in Studio. For example, the "live" layer is visible from zoom 9 by default, but I changed the style to be visible from zoom 11.

![brasilia-v2___mapbox](https://user-images.githubusercontent.com/4501388/46880528-83bf0c80-ce0e-11e8-8ef1-9856fcb9a2f7.png)

**Comment by bwellington** [comment]
Huh, so I guess minimum zoom levels are not controlled by the values in style.json?

**Comment by davidheyman** [comment]
The issue is they’re only in the vector tiles starting at zoom level 12 so this is where things don’t agree. I’ll try running them at 11 just to confirm they won’t fit at that zoom, otherwise we’ll need to update the styles so they start at 12.
