### ISSUE TITLE
Compress the timeline between 1892 and 1955

### ISSUE THREAD

**Issue by davidheyman** [axismaps/pilotplan#49]
This is something we do on diverseLevant. Between 1895 and 1955, the timeline pixel per year ratio should be 5x (or whatever looks best and is easiest) smaller than after 1955.

**Comment by bwellington** [comment]
Updated. Right now 1892 - 1955 has half the pixel per year ratio of 1955 - present. Should the labeling / time compression need to be further tweaked?

**Comment by davidheyman** [comment]
Functionally it works exactly like it should, but we need to get some additional year labels on there to communicate to the user what's happening with the dates.

@bcsheesley Can you put together a quick design that has a minimum year label for the timeline? It can also be a rounded version of that year with a tick mark if that makes it easier.

**Comment by bcsheesley** [comment]
I think ticks at 15 years and labels at 30 years in this range would show the compression.

![compression](https://user-images.githubusercontent.com/4501388/46961045-85364200-d065-11e8-8632-5d187728e9de.png)
