### ISSUE TITLE
Selecting a layer to highlight when zoomed in too far breaks the map

### ISSUE THREAD

**Issue by bwellington** [axismaps/pilotplan#5]
Selecting a layer from the sidebar when zoomed in too far causes the map to zoom into outer space and render the highlighted layer against a black screen. This appears to stem from a bug in the mapbox-gl code which causes feature geojson to be returned with bad coordinates when the zoom level is too high:

https://github.com/mapbox/mapbox-gl-js/issues/3722

We could either 1) disable layer buttons when zoomed in beyond a certain threshold, or 2) build our own API for getting feature/layer geojson

**Comment by bwellington** [comment]
Assuming we're not building our own API, how should I approach this? We can either disable layer buttons beyond a certain zoom, or we could set a max zoom level for the map.

**Comment by bcsheesley** [comment]
I've been itching for a max zoom, so if that fixes the problem, great. There's no need to zoom all the way in on some features (like small buildings) when the basemap doesn't provide any additional detail. Instead, you just lose context. Let's try max=18.

**Comment by bwellington** [comment]
I've been testing this by selecting the "park" layer for 1960. Any zoom level >= 15 causes the map to return bad geojson for the highlight layer. So a max zoom level of 14.99 appears to fix the problem, but 15 does not. I'm not sure if this is too far zoomed out to be acceptable.

**Comment by bcsheesley** [comment]
Level 14.99 is probably too far out to be the max. Does that leave disabling legend buttons as our best bet? If so, I wonder if we should make use of the same notification in #7 when zoom >15. Maybe it says something like "Zoom out for more legend options"?

The disabled state of those buttons could be made by removing the button background and binoculars icon.

**Comment by davidheyman** [comment]
Clear your cache to load in new tiles and that should have this bug fixed. The issue now is lots of features are coming back with null geometry when you click it.

**Comment by bwellington** [comment]
Ok yeah, that seems to solve it! There is still the issue that zooming in too far sometimes causes layers to not return any data. Unfortunately there really isn't a way to know beforehand if a layer will return data or not. If the user zooms in all the way and clicks a layer that returns no geojson, should there be a popup that says something like "zoom out to highlight layer"?

**Comment by bcsheesley** [comment]
I also notice that depending on zoom level, it will return some, but not necessarily all of the geometry for a feature. E.g., Parks layer, 1960. I think a popup would be okay. We'd need something to explain why the button isn't working.

**Comment by davidheyman** [comment]
18573c40 has a JSON file with SubType extent by year. It only looks for years when the SubType changed so if the year you're on isn't listed in it, look to the next previous year.

This needs some refinement, but hopefully it can get around the issue so the new zoom to code would work like:

1. Read the extents from the JSON and zoom to them (with a little padding)
2. Wait for the tiles to load
3. Read the features and draw
3a. Make any necessary adjustments to the extent (maybe, if this isn't too distracting)

**Comment by bwellington** [comment]
Updated--seems to be mostly working
