### ISSUE TITLE
Can't highlight buildings layer if your starting zoom level is lower than the min zoom for buildings

### ISSUE THREAD

**Issue by davidheyman** [axismaps/pilotplan#51]
It zooms in correctly to the buildings min zoom, but nothing highlights

**Comment by davidheyman** [comment]
I couldn’t get this to work with "Live" in 1960. The other layers worked fine, so it must be something about that particular layer that is causing it to fail.

**Comment by bwellington** [comment]
I think the issue is that I'm getting a minZoom value of 11 when I query the map for a building map layer. Is there a reason why map layer minZoom values wouldn't align with style.json?

**Comment by davidheyman** [comment]
Where are you pulling the minZoom property from? I just searched through style.json and only found `"minzoom": 12` in styles attached to roads.

**Comment by bwellington** [comment]
I was getting this with the `mbMap.getLayer()` method. But it's coming through as 12 now, so who knows.
