### ISSUE TITLE
Zoom to original bounds on rotate button click

### ISSUE THREAD

**Issue by bwellington** [axismaps/pilotplan#54]
I'm still finding it pretty easy to get lost, particularly when zooming to certain overlays. Sometimes the only way to find the city again is to manually clear the url parameters and reload the map. I'm thinking it'd make sense to have the rotate button zoom to the original (city) bounds. Thoughts?

**Comment by bcsheesley** [comment]
I would be okay with that. The existing icon is probably still applicable (rotate and zoom to the 'airplane'). At one point, we had considered adding this functionality (#3). Sounds like its more necessary now that certain overlays cause trouble.
