### ISSUE TITLE
Disable mouse events on feature highlight zoom?

### ISSUE THREAD

**Issue by bwellington** [axismaps/pilotplan#55]
I noticed that clicking on menu buttons during the feature highlight zoom process was causing issues. As a solution I've disabled all mouse events during feature highlight zooming. Is this a good solution or is it weird to temporarily lose control of the map?

**Comment by bcsheesley** [comment]
Good idea. I think that's fine. They don't last that long.

**Comment by bwellington** [comment]
Occasionally it can last a little while, like you zoom way in and then select a sector, where the map needs to zoom out and highlight in stages. But at least something is happening on screen, so it's obvious that things aren't broken.

**Comment by bcsheesley** [comment]
Agreed. Another option would be a button to cancel the process, but that seems like it could be equally weird.
