### ISSUE TITLE
No method for dealing with features that exist, then go away, then come back

### ISSUE THREAD

**Issue by davidheyman** [axismaps/pilotplan#57]
Orchards, for example, exist in 1957 only, but then don't exist again until 2016. Because we just have min / max year in the config file, they are showing up for all the years in-between.

**Comment by davidheyman** [comment]
Along these same lines, the timeline should skip years that don’t have any new data.

**Comment by fdahdah** [comment]
Ok… Can we then avoid panning when no orchards exist for a particular year?

**Comment by fdahdah** [comment]
Yes…. absolutely…  Thanks!
