### ISSUE TITLE
When clicking on a legend to highlight, only change a user’s view if no matching features are already in the view

### ISSUE THREAD

**Issue by davidheyman** [axismaps/pilotplan#60]

**Comment by davidheyman** [comment]
@bwellington This one is beyond me. Could you take it on?

**Comment by bwellington** [comment]
Sure. So does this mean the map should only highlight what's currently in view, like a fragment of the layer? It is not possible to highlight the whole layer without changing the view.

**Comment by bwellington** [comment]
The only way to highlight an entire layer without changing the view would be to build an external API

**Comment by davidheyman** [comment]
Wouldn’t the modified styles apply to newly loaded features that match the filter? The highlighting is now done by adjusting the opacity / luminosity and not by drawing a new layer on top.

**Comment by bwellington** [comment]
Oh right! Disregard everything I just wrote
