### ISSUE TITLE
Searching yields different results at different zoom levels

### ISSUE THREAD

**Issue by bwellington** [axismaps/pilotplan#7]
I am limited to querying either 1) features that are embedded in the vector tiles or, 2) features that are currently rendered in the map. #1 will always include features in #2, but is less intuitive for the user. Ideally, something like text searching would return the same results regardless of the current map extents, but there is no way around this short of building our own API.

**Comment by davidheyman** [comment]
My preference would be text searching works on everything embedded in the tiles but click / box searching only works on features that are rendered.

With that in mind, the only place we're going to get caught out is the buildings layer isn't in the tiles < 11, so text searching won't be great there.

@bcsheesley Can you put together a design for a warning message that appears below the search box when the zoom is < 11, informing users that not all features are searchable unless they zoom in?

**Comment by bcsheesley** [comment]
Maybe just something like this...

![warning](https://user-images.githubusercontent.com/4501388/45632931-24b2e580-ba64-11e8-8909-22ddba4c58b2.png)
